swagger: '2.0'
info:
  title: test
  version: "0.2.12"
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello_world:
    get:
      tags: [healthcheck liveness]
      operationId: src.main.test.hello_world
      summary: Return a 200 status if health check is successful
      responses:
        200:
          description: Liveness Health check is successful
        404:
          description: Not Found

