swagger: '2.0'
info:
  title: test
  version: "0.1.0"
consumes:
  - application/json
produces:
  - application/json
#parameters:
#  $ref: src/date/swagger.yaml
paths:
  /hello_world:
    get:
      tags: [hello_world]
      operationId: main.test.hello_world
      responses:
        200:
          description: Hello world sucessful
        404:
          description: Not Found

  /time:
    get:
      tags: [time]
      operationId: tricks.time.views.lookup
      summary: Return current time
      parameters:
      - name: uuid_COMMAND
        in: query
        description: hello
        type: string
      - name: str_LOCs
        in: query
        required: false
        type: string
      responses:
        200:
          description: time trick
        404:
          description: Error
    post:
      tags: [time]
      operationId: tricks.time.views.lookup
      requestBody:
        summary: Return current time
        consumes:
          - application/x-www-form-urlencoded
        parameters:
        - name: uuid_COMMAND
          in: formData
          description: hello
          type: string
        - name: str_LOCs
          in: query
          required: false
          type: string
        responses:
          200:
            description: time trick
          404:
            description: Error


