swagger: '2.0'
info:
  title: test
  version: "0.1.0"
consumes:
  - application/json
produces:
  - application/json
#parameters:
#  $ref: src/date/swagger.yaml
paths:
  /hello_world:
    get:
      tags: [hello_world]
      operationId: main.test.hello_world
      responses:
        200:
          description: Hello world sucessful
        404:
          description: Not Found

  /time:
    get:
      tags: [time]
      operationId: tricks.time.views.lookup
      summary: Return current time
      parameters:
      - name: uuid_COMMAND
        in: query
        description: hello
        type: string
      - name: str_LOCs
        in: query
        required: false
        type: string
      responses:
        200:
          description: time trick
        404:
          description: Error

#    post:
#      operationId: tricks.time.views.lookup
#      parameters:
#        schema:
#          type: "object"
#            required:
#            - "name"
#            properties:
#              name:
#                type: "string"
#              tag:
#                type: "string"
#      responses:
#        200:
#          description: time trick
#        404:
#          description: Error





#    post:
#      operationId: tricks.time.views.lookup
#      summary: Return current time
#      requestBody:
#        content:
#          application/x-www-form-urlencoded:
#            schema:
#              type: objects
#              properties:
#                uuid_COMMAND:
#                  type: string
#                str_LOC:
#                  type: string



#    post:
#      summary: Creates a user.
#      requestBody:
#        required: true
#        content:
#          application/x-www-form-urlencoded:
#            schema:
#              type: object
#              properties:
#                username:
#                  type: string
#      responses:
#        '201':
#          description: Created