swagger: '2.0'
info:
  title: test
  version: "0.1.0"
consumes:
  - application/json
produces:
  - application/json
#parameters:
#  $ref: src/clock/swagger.yaml
paths:
  /hello_world:
    get:
      tags: [hello_world]
      operationId: main.test.hello_world
      responses:
        200:
          description: Hello world sucessful
        404:
          description: Not Found

  /clock:
    get:
      tags: [clock]
      operationId: tricks.clock.views.lookup
      summary: Return current time
      parameters:
      - name: uuid_COMMAND
        in: query
        description: hello
        type: string
      - name: str_LOC
        in: query
        required: false
        type: string
      responses:
        200:
          description: Return clock successful
        404:
          description: Error


